#ifndef ASSEMBLE_ERROR_H_
#define ASSEMBLE_ERROR_H_

typedef enum {
    ERROR_EMPTY = 10,
    ERROR_EXPECTED_INSTRUCTION,
    ERROR_TOO_SHORT,
    ERROR_TOO_LONG,
    ERROR_INVALID_INSTRUCTION,
    ERROR_INVALID_LABEL,
    ERROR_EXPECTED_LABEL_OR_PURE_CONSTANT,
    ERROR_EXPECTED_4_DIVISIBLE,
    ERROR_CONST_OOB,
    ERROR_EXPECTED_REGISTER_OR_HASH_CONSTANT,
    ERROR_INVALID_REGISTER,
    ERROR_EXPECTED_REGISTER,
    ERROR_OFFSET_TOO_FAR,
    ERROR_EXPECTED_EQUALS_CONSTANT_OR_BRACE,
    ERROR_EXPECTED_CLOSED_BRACE,
    ERROR_EXPECTED_HASH_CONSTANT,
    ERROR_SHIFT_OOB
} ErrorCodes;

typedef enum {
    STAGE_NONE = 10,
    STAGE_DISPATCH,
    STAGE_BRANCH,
    STAGE_MULTIPLY,
    STAGE_DATA_TRANSFER,
    STAGE_SHIFTED_REGISTER
} ProcessingStage;

ErrorCodes error_code = ERROR_EMPTY;
ProcessingStage processing_stage = STAGE_NONE;

void SetErrorCode(ProcessingStage stage, ErrorCodes new_error_code);

void ReportError(int line_num, char* file_name, char* line_contents);

#endif /* ASSEMBLE_ERROR_H_ */
