all: Report Checkpoint Emulator_Video_Interface

.phony: all clean

Report:
	cd Report && $(MAKE)

Checkpoint:
	cd Checkpoint && $(MAKE)

Emulator_Video_Interface:
	cd "Emulator Video Interface" && $(MAKE)

clean:
	rm -f *.pdf
